<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FormulaSeeder extends Seeder
{
    public function run(): void
    {
        $formulas = [

            // ===================== PRIMARY MATHEMATICS =====================
            ['title' => 'Area of Rectangle',        'formula' => 'A = l × w',                                  'description' => 'Where l = length, w = width',                             'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Area of Square',            'formula' => 'A = s²',                                     'description' => 'Where s = side length',                                   'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Area of Triangle',          'formula' => 'A = ½ × b × h',                             'description' => 'Where b = base, h = perpendicular height',                'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Area of Circle',            'formula' => 'A = πr²',                                    'description' => 'Where r = radius, π ≈ 3.14159',                          'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Circumference of Circle',   'formula' => 'C = 2πr = πd',                              'description' => 'Where r = radius, d = diameter',                         'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Perimeter of Rectangle',    'formula' => 'P = 2(l + w)',                              'description' => 'Where l = length, w = width',                             'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Perimeter of Square',       'formula' => 'P = 4s',                                    'description' => 'Where s = side length',                                   'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Perimeter of Triangle',     'formula' => 'P = a + b + c',                             'description' => 'Sum of all three sides',                                  'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Volume of Cuboid',          'formula' => 'V = l × w × h',                             'description' => 'Where l = length, w = width, h = height',                'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Volume of Cube',            'formula' => 'V = s³',                                    'description' => 'Where s = side length',                                   'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Geometry'],
            ['title' => 'Simple Interest',           'formula' => 'SI = (P × R × T) / 100',                   'description' => 'Where P = Principal, R = Rate (%), T = Time (years)',    'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Arithmetic'],
            ['title' => 'Percentage',                'formula' => '% = (Part / Whole) × 100',                 'description' => 'Convert part to percentage of the whole',                 'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Arithmetic'],
            ['title' => 'Mean (Average)',            'formula' => 'Mean = Sum of values / n',                 'description' => 'n = number of values',                                    'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Statistics'],
            ['title' => 'Speed',                     'formula' => 'Speed = Distance / Time',                  'description' => 'Units: m/s or km/h',                                      'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Arithmetic'],
            ['title' => 'Distance',                  'formula' => 'Distance = Speed × Time',                  'description' => 'D = S × T',                                               'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Arithmetic'],
            ['title' => 'Time',                      'formula' => 'Time = Distance / Speed',                  'description' => 'T = D / S',                                               'subject' => 'Mathematics', 'level' => 'primary', 'category' => 'Arithmetic'],

            // ===================== SECONDARY MATHEMATICS =====================
            ['title' => 'Quadratic Formula',         'formula' => 'x = (−b ± √(b² − 4ac)) / 2a',            'description' => 'Solves ax² + bx + c = 0',                                'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Algebra'],
            ['title' => 'Pythagorean Theorem',       'formula' => 'c² = a² + b²',                             'description' => 'In a right triangle, c is the hypotenuse',               'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Slope of a Line',           'formula' => 'm = (y₂ − y₁) / (x₂ − x₁)',             'description' => 'Gradient between two points (x₁,y₁) and (x₂,y₂)',       'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Algebra'],
            ['title' => 'Equation of a Line',        'formula' => 'y = mx + c',                               'description' => 'm = gradient, c = y-intercept',                          'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Algebra'],
            ['title' => 'Distance Between Two Points','formula' => 'd = √((x₂−x₁)² + (y₂−y₁)²)',           'description' => 'Euclidean distance formula',                              'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Midpoint Formula',          'formula' => 'M = ((x₁+x₂)/2, (y₁+y₂)/2)',            'description' => 'Coordinates of the midpoint of a line segment',           'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Area of Trapezoid',         'formula' => 'A = ½(a + b)h',                           'description' => 'Where a, b are parallel sides, h = height',              'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Area of Parallelogram',     'formula' => 'A = b × h',                               'description' => 'Where b = base, h = perpendicular height',               'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Volume of Cylinder',        'formula' => 'V = πr²h',                                'description' => 'Where r = radius, h = height',                           'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Volume of Cone',            'formula' => 'V = ⅓πr²h',                              'description' => 'Where r = base radius, h = height',                      'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Volume of Sphere',          'formula' => 'V = (4/3)πr³',                            'description' => 'Where r = radius',                                       'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Surface Area of Sphere',    'formula' => 'SA = 4πr²',                               'description' => 'Total surface area of a sphere',                        'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Sine (SOH)',                 'formula' => 'sin(θ) = Opposite / Hypotenuse',          'description' => 'SOH: Sine = Opposite over Hypotenuse',                  'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Trigonometry'],
            ['title' => 'Cosine (CAH)',               'formula' => 'cos(θ) = Adjacent / Hypotenuse',          'description' => 'CAH: Cosine = Adjacent over Hypotenuse',                'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Trigonometry'],
            ['title' => 'Tangent (TOA)',              'formula' => 'tan(θ) = Opposite / Adjacent',            'description' => 'TOA: Tangent = Opposite over Adjacent',                 'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Trigonometry'],
            ['title' => 'Sine Rule',                  'formula' => 'a/sin(A) = b/sin(B) = c/sin(C)',          'description' => 'For any triangle ABC',                                   'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Trigonometry'],
            ['title' => 'Cosine Rule',                'formula' => 'a² = b² + c² − 2bc·cos(A)',              'description' => 'Relates sides and angles of any triangle',               'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Trigonometry'],
            ['title' => 'Standard Deviation',        'formula' => 'σ = √(Σ(x − x̄)² / n)',                  'description' => 'Measure of data spread around the mean',                 'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Statistics'],
            ['title' => 'Variance',                   'formula' => 'σ² = Σ(x − x̄)² / n',                   'description' => 'Square of standard deviation',                           'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Statistics'],
            ['title' => 'Arithmetic Sequence (nth term)', 'formula' => 'aₙ = a + (n−1)d',                   'description' => 'a = first term, d = common difference',                  'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Sequences'],
            ['title' => 'Sum of Arithmetic Series',  'formula' => 'Sₙ = n/2 × (2a + (n−1)d)',              'description' => 'Or Sₙ = n/2 × (first + last)',                           'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Sequences'],
            ['title' => 'Geometric Sequence (nth term)', 'formula' => 'aₙ = a·rⁿ⁻¹',                        'description' => 'a = first term, r = common ratio',                       'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Sequences'],
            ['title' => 'Sum of Geometric Series',   'formula' => 'Sₙ = a(1 − rⁿ) / (1 − r)',             'description' => 'Valid when r ≠ 1',                                        'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Sequences'],
            ['title' => 'Sum to Infinity (GP)',       'formula' => 'S∞ = a / (1 − r)',                       'description' => 'Valid when |r| < 1',                                     'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Sequences'],
            ['title' => 'Logarithm Definition',      'formula' => 'logₐ(b) = c ⟺ aᶜ = b',                  'description' => 'Base-a logarithm',                                       'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Algebra'],
            ['title' => 'Product Rule (Logs)',        'formula' => 'log(ab) = log(a) + log(b)',              'description' => 'Logarithm of a product',                                 'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Algebra'],
            ['title' => 'Quotient Rule (Logs)',       'formula' => 'log(a/b) = log(a) − log(b)',            'description' => 'Logarithm of a quotient',                               'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Algebra'],
            ['title' => 'Power Rule (Logs)',          'formula' => 'log(aⁿ) = n·log(a)',                    'description' => 'Logarithm of a power',                                   'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Algebra'],
            ['title' => 'Change of Base',             'formula' => 'logₐ(b) = log(b) / log(a)',             'description' => 'Convert between logarithm bases',                       'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Algebra'],
            ['title' => 'Interior Angles of Polygon', 'formula' => 'Sum = (n − 2) × 180°',                 'description' => 'n = number of sides',                                    'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Geometry'],
            ['title' => 'Compound Interest',         'formula' => 'A = P(1 + r/n)^(nt)',                   'description' => 'P = principal, r = rate, n = compounds per year, t = years', 'subject' => 'Mathematics', 'level' => 'secondary', 'category' => 'Arithmetic'],

            // ===================== SECONDARY PHYSICS =====================
            ['title' => "Newton's 2nd Law",          'formula' => 'F = ma',                                  'description' => 'Force = mass × acceleration (N = kg·m/s²)',              'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Mechanics'],
            ['title' => 'Weight',                     'formula' => 'W = mg',                                  'description' => 'W = weight (N), m = mass (kg), g = 9.8 m/s²',           'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Mechanics'],
            ['title' => 'Work Done',                  'formula' => 'W = Fd·cos(θ)',                          'description' => 'F = force, d = displacement, θ = angle between them',    'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Mechanics'],
            ['title' => 'Kinetic Energy',             'formula' => 'KE = ½mv²',                              'description' => 'm = mass (kg), v = velocity (m/s)',                      'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Mechanics'],
            ['title' => 'Gravitational Potential Energy', 'formula' => 'PE = mgh',                           'description' => 'm = mass, g = 9.8 m/s², h = height',                    'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Mechanics'],
            ['title' => 'Power',                      'formula' => 'P = W/t',                                 'description' => 'P = power (W), W = work done (J), t = time (s)',        'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Mechanics'],
            ['title' => 'Velocity (uniform accel)',   'formula' => 'v = u + at',                              'description' => 'u = initial velocity, a = acceleration, t = time',      'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Kinematics'],
            ['title' => 'Displacement (SUVAT)',       'formula' => 's = ut + ½at²',                          'description' => 'u = initial velocity, a = acceleration, t = time',      'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Kinematics'],
            ['title' => 'SUVAT: v² equation',        'formula' => 'v² = u² + 2as',                          'description' => 's = displacement, a = acceleration',                    'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Kinematics'],
            ['title' => 'Pressure',                   'formula' => 'P = F/A',                                 'description' => 'P = pressure (Pa), F = force (N), A = area (m²)',      'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Mechanics'],
            ['title' => 'Density',                    'formula' => 'ρ = m/V',                                 'description' => 'ρ (rho) = density, m = mass, V = volume',               'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Mechanics'],
            ['title' => "Ohm's Law",                  'formula' => 'V = IR',                                  'description' => 'V = voltage (V), I = current (A), R = resistance (Ω)', 'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Electricity'],
            ['title' => 'Electrical Power',           'formula' => 'P = VI = I²R = V²/R',                   'description' => 'Three equivalent forms of electrical power',             'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Electricity'],
            ['title' => 'Electric Charge',            'formula' => 'Q = It',                                  'description' => 'Q = charge (C), I = current (A), t = time (s)',         'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Electricity'],
            ['title' => 'Wave Speed',                 'formula' => 'v = fλ',                                  'description' => 'v = speed (m/s), f = frequency (Hz), λ = wavelength (m)', 'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Waves'],
            ['title' => 'Period and Frequency',       'formula' => 'T = 1/f',                                 'description' => 'T = period (s), f = frequency (Hz)',                    'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Waves'],
            ['title' => "Snell's Law",                'formula' => 'n₁·sin(θ₁) = n₂·sin(θ₂)',              'description' => 'Law of refraction; n = refractive index',               'subject' => 'Physics', 'level' => 'secondary', 'category' => 'Optics'],

            // ===================== SECONDARY CHEMISTRY =====================
            ['title' => 'Number of Moles',           'formula' => 'n = m/M',                                 'description' => 'n = moles, m = mass (g), M = molar mass (g/mol)',       'subject' => 'Chemistry', 'level' => 'secondary', 'category' => 'Stoichiometry'],
            ['title' => 'Concentration',              'formula' => 'c = n/V',                                 'description' => 'c = mol/L, n = moles, V = volume in litres',            'subject' => 'Chemistry', 'level' => 'secondary', 'category' => 'Stoichiometry'],
            ['title' => 'pH Scale',                   'formula' => 'pH = −log[H⁺]',                          'description' => '[H⁺] = molar concentration of hydrogen ions',           'subject' => 'Chemistry', 'level' => 'secondary', 'category' => 'Acids & Bases'],
            ['title' => 'pOH',                        'formula' => 'pOH = −log[OH⁻]',                        'description' => 'pH + pOH = 14 at 25°C',                                  'subject' => 'Chemistry', 'level' => 'secondary', 'category' => 'Acids & Bases'],

            // ===================== HIGH SCHOOL MATHEMATICS =====================
            ['title' => 'Derivative of xⁿ',          'formula' => 'd/dx(xⁿ) = nxⁿ⁻¹',                      'description' => 'Power rule of differentiation',                          'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Derivative of sin(x)',       'formula' => 'd/dx(sin x) = cos x',                    'description' => 'Derivative of sine function',                            'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Derivative of cos(x)',       'formula' => 'd/dx(cos x) = −sin x',                  'description' => 'Derivative of cosine function',                         'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Derivative of eˣ',           'formula' => 'd/dx(eˣ) = eˣ',                          'description' => 'The exponential function is its own derivative',        'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Derivative of ln(x)',        'formula' => 'd/dx(ln x) = 1/x',                       'description' => 'Derivative of natural logarithm',                       'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Chain Rule',                 'formula' => 'dy/dx = (dy/du)·(du/dx)',                'description' => 'Differentiate composite functions',                     'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Product Rule',               'formula' => 'd/dx(uv) = u\'v + uv\'',                 'description' => 'Differentiate a product of two functions',              'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Quotient Rule',              'formula' => 'd/dx(u/v) = (u\'v − uv\') / v²',        'description' => 'Differentiate a quotient of two functions',              'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Integral of xⁿ',            'formula' => '∫xⁿ dx = xⁿ⁺¹/(n+1) + C',             'description' => 'Power rule of integration (n ≠ −1)',                     'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Integral of 1/x',           'formula' => '∫(1/x) dx = ln|x| + C',                 'description' => 'Natural log integral',                                   'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Integral of sin(x)',         'formula' => '∫sin(x) dx = −cos(x) + C',              'description' => 'Integral of sine',                                       'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Integral of cos(x)',         'formula' => '∫cos(x) dx = sin(x) + C',               'description' => 'Integral of cosine',                                     'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Fundamental Theorem of Calculus', 'formula' => '∫ₐᵇ f(x)dx = F(b) − F(a)',       'description' => 'F is the antiderivative of f',                           'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Integration by Parts',       'formula' => '∫u dv = uv − ∫v du',                    'description' => 'For integrating products of functions',                  'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Calculus'],
            ['title' => 'Pythagorean Identity',       'formula' => 'sin²(x) + cos²(x) = 1',                 'description' => 'Fundamental trigonometric identity',                    'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Trigonometry'],
            ['title' => '1 + tan²(x) = sec²(x)',     'formula' => '1 + tan²(x) = sec²(x)',                  'description' => 'Derived from Pythagorean identity',                     'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Trigonometry'],
            ['title' => 'Double Angle: sin(2x)',      'formula' => 'sin(2x) = 2sin(x)cos(x)',                'description' => 'Double angle formula for sine',                          'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Trigonometry'],
            ['title' => 'Double Angle: cos(2x)',      'formula' => 'cos(2x) = cos²(x) − sin²(x)',           'description' => 'Also: cos(2x) = 1 − 2sin²(x) = 2cos²(x) − 1',         'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Trigonometry'],
            ['title' => 'Addition Formula: sin(A±B)', 'formula' => 'sin(A±B) = sinA·cosB ± cosA·sinB',     'description' => 'Sine addition/subtraction formula',                     'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Trigonometry'],
            ['title' => 'Addition Formula: cos(A±B)', 'formula' => 'cos(A±B) = cosA·cosB ∓ sinA·sinB',     'description' => 'Cosine addition/subtraction formula',                   'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Trigonometry'],
            ['title' => 'Permutations',               'formula' => 'P(n,r) = n! / (n−r)!',                  'description' => 'Ordered arrangements of r items from n',                'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Combinatorics'],
            ['title' => 'Combinations',               'formula' => 'C(n,r) = n! / (r!(n−r)!)',              'description' => 'Unordered selections of r items from n',                'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Combinatorics'],
            ['title' => 'Binomial Theorem',           'formula' => '(a+b)ⁿ = Σ C(n,k)·aⁿ⁻ᵏ·bᵏ',           'description' => 'Expansion of (a+b)ⁿ',                                   'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Algebra'],
            ['title' => 'Complex Number Modulus',     'formula' => '|z| = √(a² + b²)',                       'description' => 'z = a + bi is a complex number',                        'subject' => 'Mathematics', 'level' => 'highschool', 'category' => 'Complex Numbers'],

            // ===================== HIGH SCHOOL PHYSICS =====================
            ['title' => 'Gravitational Force',        'formula' => 'F = Gm₁m₂/r²',                          'description' => 'G = 6.674×10⁻¹¹ N·m²/kg², r = distance',             'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Gravitation'],
            ['title' => 'Centripetal Force',          'formula' => 'F = mv²/r = mω²r',                       'description' => 'For circular motion, r = radius, ω = angular velocity','subject' => 'Physics', 'level' => 'highschool', 'category' => 'Mechanics'],
            ['title' => 'Angular Velocity',           'formula' => 'ω = 2π/T = 2πf',                         'description' => 'T = period, f = frequency',                              'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Mechanics'],
            ['title' => "Coulomb's Law",              'formula' => 'F = kq₁q₂/r²',                           'description' => 'k = 8.99×10⁹ N·m²/C², q = charges, r = distance',    'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Electricity'],
            ['title' => 'Electric Field',             'formula' => 'E = F/q = kQ/r²',                        'description' => 'E = electric field strength (N/C)',                    'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Electricity'],
            ['title' => 'Capacitance',                'formula' => 'C = Q/V',                                 'description' => 'C = capacitance (F), Q = charge (C), V = voltage (V)','subject' => 'Physics', 'level' => 'highschool', 'category' => 'Electricity'],
            ['title' => "Faraday's Law",              'formula' => 'EMF = −N·dΦ/dt',                         'description' => 'N = turns, Φ = magnetic flux',                          'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Electromagnetism'],
            ['title' => 'Transformer Equation',       'formula' => 'V₁/V₂ = N₁/N₂',                         'description' => 'Voltage ratio = turns ratio',                           'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Electromagnetism'],
            ['title' => 'Radioactive Decay',          'formula' => 'N = N₀·e^(−λt)',                         'description' => 'N = remaining nuclei, λ = decay constant',              'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Nuclear Physics'],
            ['title' => 'Half-Life',                  'formula' => 'T₁/₂ = ln(2)/λ = 0.693/λ',              'description' => 'Time for half the nuclei to decay',                     'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Nuclear Physics'],
            ['title' => 'Mass-Energy Equivalence',    'formula' => 'E = mc²',                                 'description' => 'c = 3×10⁸ m/s (speed of light)',                       'subject' => 'Physics', 'level' => 'highschool', 'category' => 'Nuclear Physics'],

            // ===================== HIGH SCHOOL CHEMISTRY =====================
            ['title' => 'Ideal Gas Law',              'formula' => 'PV = nRT',                                'description' => 'P=pressure, V=volume, n=moles, R=8.314 J/mol·K, T=temp (K)', 'subject' => 'Chemistry', 'level' => 'highschool', 'category' => 'Gas Laws'],
            ['title' => "Boyle's Law",                'formula' => 'P₁V₁ = P₂V₂',                           'description' => 'At constant temperature and amount',                    'subject' => 'Chemistry', 'level' => 'highschool', 'category' => 'Gas Laws'],
            ['title' => "Charles's Law",              'formula' => 'V₁/T₁ = V₂/T₂',                         'description' => 'At constant pressure; T in Kelvin',                     'subject' => 'Chemistry', 'level' => 'highschool', 'category' => 'Gas Laws'],
            ['title' => 'Empirical Formula',          'formula' => 'Mole ratio = mass/M',                    'description' => 'Find ratio using mass and molar mass',                   'subject' => 'Chemistry', 'level' => 'highschool', 'category' => 'Stoichiometry'],

            // ===================== UNIVERSITY MATHEMATICS =====================
            ['title' => 'Taylor Series',              'formula' => 'f(x) = Σ [f⁽ⁿ⁾(a)/n!]·(x−a)ⁿ',        'description' => 'Infinite series expansion around point a',               'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Calculus'],
            ['title' => "Maclaurin Series for eˣ",   'formula' => 'eˣ = Σ xⁿ/n! = 1 + x + x²/2! + ...',  'description' => 'Taylor series of eˣ around 0',                          'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Calculus'],
            ['title' => "L'Hôpital's Rule",           'formula' => 'lim f/g = lim f\'/g\'',                  'description' => 'For 0/0 or ∞/∞ indeterminate forms',                   'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Calculus'],
            ['title' => 'Determinant of 2×2 Matrix', 'formula' => 'det(A) = ad − bc for A = [[a,b],[c,d]]','description' => 'Also written as |A|',                                   'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Linear Algebra'],
            ['title' => 'Eigenvalue Equation',        'formula' => 'Av = λv  ⟹  det(A − λI) = 0',          'description' => 'v = eigenvector, λ = eigenvalue',                       'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Linear Algebra'],
            ['title' => 'Normal Distribution',        'formula' => 'f(x) = (1/σ√(2π))·e^(−(x−μ)²/2σ²)',  'description' => 'μ = mean, σ = standard deviation',                     'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Statistics'],
            ['title' => "Bayes' Theorem",             'formula' => 'P(A|B) = P(B|A)·P(A) / P(B)',           'description' => 'Posterior probability given prior and likelihood',       'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Statistics'],
            ['title' => 'Fourier Transform',          'formula' => 'F(ω) = ∫₋∞^∞ f(t)e^(−iωt) dt',        'description' => 'Converts time-domain signal to frequency domain',       'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Analysis'],
            ['title' => 'Euler\'s Identity',          'formula' => 'e^(iπ) + 1 = 0',                         'description' => 'Combines e, i, π, 1, and 0',                            'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Complex Analysis'],
            ['title' => "Stokes' Theorem",            'formula' => '∮∂S F·dr = ∬S (∇×F)·dS',              'description' => 'Relates line integral to surface integral',              'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Vector Calculus'],
            ['title' => 'Divergence Theorem',         'formula' => '∯∂V F·dA = ∭V (∇·F) dV',              'description' => "Gauss's theorem: relates surface to volume integral",    'subject' => 'Mathematics', 'level' => 'university', 'category' => 'Vector Calculus'],

            // ===================== UNIVERSITY PHYSICS =====================
            ['title' => "Gauss's Law (Electric)",    'formula' => '∇·E = ρ/ε₀',                             'description' => 'First of Maxwell\'s equations; ρ = charge density',    'subject' => 'Physics', 'level' => 'university', 'category' => 'Electromagnetism'],
            ['title' => "Gauss's Law (Magnetic)",    'formula' => '∇·B = 0',                                 'description' => 'No magnetic monopoles exist',                            'subject' => 'Physics', 'level' => 'university', 'category' => 'Electromagnetism'],
            ['title' => "Faraday's Law (Maxwell)",   'formula' => '∇×E = −∂B/∂t',                           'description' => 'Changing magnetic field induces electric field',        'subject' => 'Physics', 'level' => 'university', 'category' => 'Electromagnetism'],
            ['title' => "Ampère-Maxwell Law",        'formula' => '∇×B = μ₀J + μ₀ε₀(∂E/∂t)',              'description' => 'Fourth of Maxwell\'s equations',                        'subject' => 'Physics', 'level' => 'university', 'category' => 'Electromagnetism'],
            ['title' => "Schrödinger Equation",      'formula' => 'iℏ ∂ψ/∂t = Ĥψ',                         'description' => 'Time-dependent quantum mechanics equation',              'subject' => 'Physics', 'level' => 'university', 'category' => 'Quantum Mechanics'],
            ['title' => "First Law of Thermodynamics", 'formula' => 'ΔU = Q − W',                           'description' => 'ΔU = change in internal energy, Q = heat, W = work',   'subject' => 'Physics', 'level' => 'university', 'category' => 'Thermodynamics'],
            ['title' => 'Entropy Change',             'formula' => 'dS = dQ_rev / T',                        'description' => 'S = entropy, T = absolute temperature',                'subject' => 'Physics', 'level' => 'university', 'category' => 'Thermodynamics'],
            ['title' => 'Planck\'s Equation',        'formula' => 'E = hf',                                  'description' => 'E = energy, h = 6.626×10⁻³⁴ J·s, f = frequency',     'subject' => 'Physics', 'level' => 'university', 'category' => 'Quantum Mechanics'],
            ['title' => 'de Broglie Wavelength',     'formula' => 'λ = h/p = h/mv',                         'description' => 'Wave-particle duality; p = momentum',                   'subject' => 'Physics', 'level' => 'university', 'category' => 'Quantum Mechanics'],
        ];

        $now = now();
        $rows = array_map(fn($f) => array_merge($f, ['created_at' => $now, 'updated_at' => $now]), $formulas);

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('formulas')->insert($chunk);
        }
    }
}
