services:
  - type: web
    name: math-edu-app
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force || true
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
