services:
  - type: web
    name: math-edu-app
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force || true
    startCommand: php artisan serve --host 0.0.0.0 --port 8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://math-edu-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1f1487gi27c7386ju00-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: math_db_n86b
      - key: DB_USERNAME
        value: math_user
      - key: DB_PASSWORD
        value: fmM1bTFG41DailykbQiFNPm374x8yicf

